# 最简单的清单 - 使用本地主机
[local]
localhost ansible_connection=local

# 如果要连接远程主机，取消注释并修改
[robots]
robot5 ansible_host=10.11.107.25 ansible_user=ga robot_name=S1_5 robot_sn=10000005
robot10 ansible_host=10.11.106.30 ansible_user=ga robot_name=S1_10 robot_sn=10000010
robot26 ansible_host=10.11.106.144 ansible_user=ga robot_name=S1_26 robot_sn=10000026
robot30 ansible_host=10.11.107.132 ansible_user=ga robot_name=S1_30 robot_sn=10000030
robot42 ansible_host=10.11.106.224 ansible_user=ga robot_name=S1_42 robot_sn=10000042
robot43 ansible_host=10.11.106.226 ansible_user=ga robot_name=S1_43 robot_sn=10000043

[robots:vars]
app_name=robot_task
ansible_ssh_private_key_file=~/.ssh/ansible_id_rsa
# sudo 密码（如果需要，取消注释并设置密码）
ansible_become_password=ga
